# NumPy 101
This notebook introduces the NumPy array, the fundamental data structure of NumPy
* Demonstrate the advantages of NumPy arrays over Python lists/tuples
* Review the functions used to create NumPy arrays
* Review a few functions used to describe NumPy arrays

Resource: https://scipy-lectures.org/intro/numpy/index.html

---

### Importing NumPy
NumPy is traditionally imported as `np`

In [1]:
import numpy as np

### What is a NumPy array?
A NumPy array is similar to a Python list. A key exception, however, is that while Python lists can contain any mixture of objects, the objects in a NumPy array **have to all be of the same type**. 

In [2]:
#Create a numpy array from a supplied list of numbers
a = np.array([10, 4, 12, -3])
a

array([10,  4, 12, -3])

In [3]:
#The arrays `dtype` property holds it data type
a.dtype

dtype('int32')

► Try adding a decimal to one of the numbers the statement above that creates the array. 
* Does this change the arrays `dtype`? 
* What happens if you set one item to a character?

### NumPy arrays can have *dimensions*
NumPy is built around ndarrays objects, which are high-performance multi-dimensional array data structures. Intuitively, we can think of a one-dimensional NumPy array as a data structure to represent a vector of elements – you may think of it as a fixed-size Python list where all elements share the same type. 

Similarly, we can think of a two-dimensional array as a data structure to represent a matrix or a Python list of lists. While NumPy arrays can have up to 32 dimensions if it was compiled without alterations to the source code, we will focus on lower-dimensional arrays for the purpose of illustration in this introduction.

Now, let us get started with NumPy by calling the array function to create a two-dimensional NumPy array, consisting of two rows and three columns, from a list of lists:

##### 1D array (aka "Vector")

In [4]:
#Create a one-dimensional array, i.e. a Vector
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [5]:
#The array's `ndim` property indicates the number of dimensions
a.ndim

1

In [6]:
#The array's `shape` property stores how many items in each dimension
a.shape

(4,)

##### 2D/3D array
Now let's add some dimensions. (A 2d array is often called a *matrix*...). As mentioned above, mutidimensional arrays can be envisioned as lists of lists...

In [7]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
#Reveal how may dimensions this array has
b.ndim

2

In [9]:
#Reveal how many items in each dimension
b.shape

(2, 3)

In the 2 dimensional array we just created, we have 2 items in the first dimension or axis, and 3 in the second. By convention, this is represented as a array with 2 rows and 3 columns. 

We can use the `reshape()` function to reshape our array into any other shape that retains the same number of elements in the original array. 

In [10]:
#Reshape the 2x3 array into one with 3 rows and two columns
c = b.reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
#Reveal the dimensions of the newly reshaped array
c.ndim

2

► What other shapes can we create from our array? Can you reshape it into a 1 dimensional array? A 3D array?

In [22]:
#three dimensions
d = b.reshape(1,2,3)
d
d.ndim

#one dimension
e = b.reshape(6)
e.ndim

1

### Special arrays
NumPy has a number of functions to create special arrays. We review a number of them here.

##### Evenly spaced (min, max, and step)

In [ ]:
a = np.arange(10) # 0 .. n-1  (!)
a

In [ ]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

##### Evenly spaced (min, max, and number of values)

In [ ]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

In [ ]:
d = np.linspace(0, 1, 5, endpoint=False)
d

##### Arrays of all 1s, zeros, "eye", "diag"

In [ ]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

In [ ]:
b = np.zeros((2, 2))
b

In [ ]:
c = np.eye(3)
c

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
d

##### Arrays of random values

In [ ]:
a = np.random.rand(4)       # uniform in [0, 1]
a  

In [ ]:
b = np.random.randn(4)      # Gaussian
b  

In [ ]:
np.random.seed(1234)        # Setting the random seed